version: '2.2'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/appuser
      SPRING_DATASOURCE_USERNAME: appuser
      SPRING_DATASOURCE_PASSWORD: password
  db:
    image: postgres:12
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: -c 'log_statement=all'
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db-data-volume:/var/lib/postgresql/data

volumes:
  db-data-volume:
