spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/appuser
    username: appuser
    password: password
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    root: INFO
